site_name: My Docs

theme:
  name: "material"
  palette:
    scheme: slate
    primary: black
    accent: deep purple
  logo: pillargg.png
  favicon: pillargg.png
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/pillargg/pillar-api-wrapper
repo_name: pillargg/pillar-api-wrapper

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering: 
          show_sources: false
      watch:
        - pillar